name: Publish on GitHub, CurseForge & Modrinth

on:
  workflow_dispatch:
  push:
    branches: [ release ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep "^version" gradle.properties | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish (GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "v${{steps.get_version.outputs.version}}"
          github-token: "${{secrets.GH_TOKEN}}"

          name: "${{steps.get_version.outputs.version}}"
          version: "${{steps.get_version.outputs.version}}"
          version-type: release

          changelog-file: CHANGELOG.*

          files: |
            neoforge/build/libs/*${{steps.get_version.outputs.version}}.jar
            fabric/build/libs/*${{steps.get_version.outputs.version}}.jar
            forge/build/libs/*${{steps.get_version.outputs.version}}.jar

      - name: Publish (Fabric/Quilt)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1152847
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: 1ury0R3s
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "Fabirc/Quilt ${{steps.get_version.outputs.version}}"
          version: "${{steps.get_version.outputs.version}}"
          version-type: release
          game-version-filter: any
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          loaders: |
            fabric
            quilt
          changelog-file: CHANGELOG.*

          game-versions: ">=1.20.5"
          java: 21

          files: fabric/build/libs/*${{steps.get_version.outputs.version}}.jar

      - name: Publish (Forge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1152847
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: 1ury0R3s
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "Forge ${{steps.get_version.outputs.version}}"
          version: "${{steps.get_version.outputs.version}}"
          version-type: release
          game-version-filter: any
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          loaders: |
            forge
          changelog-file: CHANGELOG.*

          game-versions: ">=1.20.5"
          java: 21

          files: forge/build/libs/*${{steps.get_version.outputs.version}}.jar


      - name: Publish (Neoforge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1152847
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          modrinth-id: 1ury0R3s
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          github-tag: "v${{steps.get_version.outputs.version}}"
          github-token: "${{secrets.GH_TOKEN}}"

          name: "Neoforge ${{steps.get_version.outputs.version}}"
          version: "${{steps.get_version.outputs.version}}"
          version-type: release
          game-version-filter: any
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          loaders: |
            neoforge
          changelog-file: CHANGELOG.*

          game-versions: ">=1.20.5"
          java: 21

          files: neoforge/build/libs/*${{steps.get_version.outputs.version}}.jar
